# Generated by Django 2.1.3 on 2019-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('dodge_chance', models.IntegerField()),
                ('critic_chance', models.IntegerField()),
                ('health', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('minimal_level', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
