# Generated by Django 2.1.3 on 2019-01-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='user',
            new_name='owner',
        ),
    ]
