# Generated by Django 2.1.3 on 2019-01-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
