# Generated by Django 2.1.3 on 2019-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190115_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='critic_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='dodge_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='critic_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='dodge_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='health',
            field=models.IntegerField(default=0),
        ),
    ]
