# Generated by Django 2.1.5 on 2019-01-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_newitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NewHero'),
        ),
    ]
