# Generated by Django 2.1.5 on 2019-01-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190129_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herostatistic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NewHero'),
        ),
        migrations.AlterField(
            model_name='itemstatistics',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NewItem'),
        ),
    ]
