# Generated by Django 2.1.3 on 2019-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190115_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='health',
            field=models.IntegerField(default=10),
        ),
    ]
