# Generated by Django 2.1.5 on 2019-01-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190129_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemStatistics',
            new_name='ItemStatistic',
        ),
    ]
